name: Update result

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL}}
      GOOGLE_PRIVATE_KEY: ${{secrets.GOOGLE_PRIVATE_KEY}}

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2.1.2
        with:
          node-version: lts
          cache: 'yarn'

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: yarn install --frozen-lockfile

      - name: Build production ğŸš§
        run: yarn fetch:result

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update result.json'
          default_author: github_actions
